---
# BOSSBAR CONFIGURATION #
# ===================== #
head-message: "BossBar"
changing-messages:
 - "{0%}§l§eSet this bar announcements on config.yml file!"
 - "{10%}§l§eWhat are you waiting for?"
 - "{50%}§l§cLooks like you're having fun with BossBar"
 - "{100%}§l§cLegends never surrendered"
change-speed: 8
worlds: []
...
